### ISSUE TITLE
Resolve controllers deeper than 1 level to avoid clashes

### ISSUE THREAD

**Issue by pointybeard** [pointybeard/api_framework#5]
Currently controllers are resolved using the page handle only, and not the entire path.

### Current Behaviour

A page `/apple/` will resolve to a controller called `ContollerApple.php`. And `/apple/banana/` will resolve to `ControllerBanana.php`. However if there was another page called banana, e.g. `/orange/banana/`, it will also resolve to that controller (`ControllerBanana.php`).

### Expected Behaviour

The controller name should be constructed based on the entire path. E.g. `/orange/banana/` should be something like `ControllerOrangeBanana.php`. This will avoid conflicts if there is another page called `banana`

**Comment by brendo** [comment]
What about encouraging PSR-4 structure in the Controller's directory?

**Comment by pointybeard** [comment]
Certainly. I've already been working on this, but it hasn't made it to GitHub just yet. I needed a quick fix based for the existing code, and this was the easiest way for now. For the most part, this extension has been sitting around gathering dust, but I found an excuse to use it on a project and spend a few hours fixing some 'low hanging fruit'.
