### ISSUE TITLE
Unnecessary escaping of some characters

### ISSUE THREAD

**Issue by pointybeard** [pointybeard/api_framework#8]
It appears something is escaping characters when it shouldn't be. E.g.

```
<data>
  <message>This is a test</message>
  <path>/one/two/three</path>
</data>
```

Results in

```
{
    "message": "This is a test",
    "path": "\/one\/two\/three"
}
```

There is no reason for the forward slashes to have been escaped like this.

**Comment by brendo** [comment]
That'll be `json_encode` :) https://3v4l.org/UgMGL

You can use `JSON_UNESCAPED_SLASHES` to prevent the behaviour  https://3v4l.org/K3oLo

**Comment by pointybeard** [comment]
Ha, wow, you're quick. Yeah I just realised that and was about to close this non-issue. :)
